### PR TITLE
# test_pull_request

### PR DESCRIPTION
**Pull request by GodaimeSan22**
dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

**Review by do-androids-dream — APPROVED** [review]
test

**Review by romanmyko — APPROVED** [review]
test

**Review by do-androids-dream — APPROVED** [review]
test test test

**Comment by Anorhayz** [comment]
Test

**Review by cyber-dhampir — COMMENTED** [review]
Test

**Review by romanmyko — APPROVED** [review]

**Review by cyber-dhampir — APPROVED** [review]
Test

**Review by romanmyko — APPROVED** [review]

**Pull request closed without merging**
